API 7.0
telegraf/types pull request #1
Opened 2023-12-30 16:40 UTC by MKRhere

This is a massive API update. This was independently updated from Bot API changelog, and cross-verified against https://github.com/grammyjs/types/pull/32.

2023-12-30 21:30 UTC, hypernova7 approved these changes

2024-02-07 22:49 UTC, dcdunkan requested changes

2024-02-07 22:49 UTC, dcdunkan commented on message.ts
> +  /** If the message to be replied to is from a different chat, unique identifier for the chat or username of the channel (in the format @channelusername) */
```suggestion
  /** If the message to be replied to is from a different chat, unique identifier for the chat or username of the channel (in the format `@channelusername`) */
```

2024-02-07 22:49 UTC, dcdunkan commented on message.ts
> +  entities: MessageEntity[];
```suggestion
  entities?: MessageEntity[];
```
`entities` is also marked as optional: https://core.telegram.org/bots/api#textquote

2024-02-07 22:49 UTC, dcdunkan commented on methods.ts
>      allow_sending_without_reply?: boolean;
```suggestion
```

This was also replaced by `reply_parameters`.

2024-02-07 22:49 UTC, dcdunkan commented on methods.ts
> +    /** Unique identifier for the target chat or username of the target channel (in the format @channelusername) */
```suggestion
    /** Unique identifier for the target chat or username of the target channel (in the format `@channelusername`) */
```

2024-02-07 22:49 UTC, dcdunkan commented on methods.ts
> +    /** Unique identifier for the chat where the original messages were sent (or channel username in the format @channelusername) */
```suggestion
    /** Unique identifier for the chat where the original messages were sent (or channel username in the format `@channelusername`) */
```

2024-02-07 22:49 UTC, dcdunkan commented on message.ts
> +  premium_subscription_month_count: number;
```suggestion
  /** The number of months the Telegram Premium subscription won from the giveaway will be active for */
  premium_subscription_month_count?: number;
```

Optional. https://core.telegram.org/bots/api#giveaway

2024-02-07 22:49 UTC, dcdunkan commented on message.ts
> +  unclaimed_prize_count: number;
```suggestion
  /** The number of other chats the user had to join in order to be eligible for the giveaway */
  additional_chat_count?: number;
  /** The number of months the Telegram Premium subscription won from the giveaway will be active for */
  premium_subscription_month_count?: number;
  /** Number of undistributed prizes */
  unclaimed_prize_count?: number;
```

2024-02-07 22:49 UTC, dcdunkan commented on message.ts
> +  unclaimed_prize_count: number;
```suggestion
  /** Number of undistributed prizes */
  unclaimed_prize_count?: number;
```

2024-02-07 22:49 UTC, dcdunkan commented on methods.ts
> +    /** Unique identifier for the chat or username of the channel (in the format @channelusername) */
```suggestion
    /** Unique identifier for the chat or username of the channel (in the format `@channelusername`) */
```

2024-02-08 07:22 UTC, merged