Add support for API 7.3 to 7.8
telegraf/types pull request #6
Opened 2024-08-02 01:13 UTC by danielrhodes

Based on https://core.telegram.org/bots/api-changelog

2025-01-06 07:12 UTC, hypernova7 approved these changes

2025-01-07 00:43 UTC, hameda169 requested changes
It seems this change is missed based on the [change log](https://core.telegram.org/bots/api-changelog#july-31-2024):
> Added the field has_main_web_app to the class [User](https://core.telegram.org/bots/api#user), which is returned in the response to [getMe](https://core.telegram.org/bots/api#getme).

2025-01-07 00:43 UTC, hameda169 commented on methods.ts
>      options: readonly string[];
Type of this parameter is changed based on the [change log](https://core.telegram.org/bots/api-changelog#may-6-2024):
> Added the class [InputPollOption](https://core.telegram.org/bots/api#inputpolloption) and changed the type of the parameter options in the method [sendPoll](https://core.telegram.org/bots/api#sendpoll) to Array of [InputPollOption](https://core.telegram.org/bots/api#inputpolloption).

2025-01-07 00:43 UTC, hameda169 commented on message.ts
> +    show_caption_above_media?: boolean;
Based on the type of [Message](https://core.telegram.org/bots/api#message):
```diff
-     show_caption_above_media?: boolean;
+     show_caption_above_media?: true;

```

2025-01-07 00:43 UTC, hameda169 commented on methods.ts
> +  show_caption_above_media?: boolean;
`InputMediaDocument` isn't included in the classes that need `show_caption_above_media` as their field based on the [change log](https://core.telegram.org/bots/api-changelog#may-28-2024):
> Added the field show_caption_above_media to the classes [Message](https://core.telegram.org/bots/api#message), [InputMediaAnimation](https://core.telegram.org/bots/api#inputmediaanimation), [InputMediaPhoto](https://core.telegram.org/bots/api#inputmediaphoto), [InputMediaVideo](https://core.telegram.org/bots/api#inputmediavideo), [InlineQueryResultGif](https://core.telegram.org/bots/api#inlinequeryresultgif), [InlineQueryResultMpeg4Gif](https://core.telegram.org/bots/api#inlinequeryresultmpeg4gif), [InlineQueryResultPhoto](https://core.telegram.org/bots/api#inlinequeryresultphoto), [InlineQueryResultVideo](https://core.telegram.org/bots/api#inlinequeryresultvideo), [InlineQueryResultCachedGif](https://core.telegram.org/bots/api#inlinequeryresultcachedgif), [InlineQueryResultCachedMpeg4Gif](https://core.telegram.org/bots/api#inlinequeryresultcachedmpeg4gif), [InlineQueryResultCachedPhoto](https://core.telegram.org/bots/api#inlinequeryresultcachedphoto), and [InlineQueryResultCachedVideo](https://core.telegram.org/bots/api#inlinequeryresultcachedvideo).

2025-01-07 00:43 UTC, hameda169 commented on methods.ts
> +  show_caption_above_media?: boolean;
`InputMediaAudio` isn't included in the classes that need `show_caption_above_media` as their field based on the [change log](https://core.telegram.org/bots/api-changelog#may-28-2024):
> Added the field show_caption_above_media to the classes [Message](https://core.telegram.org/bots/api#message), [InputMediaAnimation](https://core.telegram.org/bots/api#inputmediaanimation), [InputMediaPhoto](https://core.telegram.org/bots/api#inputmediaphoto), [InputMediaVideo](https://core.telegram.org/bots/api#inputmediavideo), [InlineQueryResultGif](https://core.telegram.org/bots/api#inlinequeryresultgif), [InlineQueryResultMpeg4Gif](https://core.telegram.org/bots/api#inlinequeryresultmpeg4gif), [InlineQueryResultPhoto](https://core.telegram.org/bots/api#inlinequeryresultphoto), [InlineQueryResultVideo](https://core.telegram.org/bots/api#inlinequeryresultvideo), [InlineQueryResultCachedGif](https://core.telegram.org/bots/api#inlinequeryresultcachedgif), [InlineQueryResultCachedMpeg4Gif](https://core.telegram.org/bots/api#inlinequeryresultcachedmpeg4gif), [InlineQueryResultCachedPhoto](https://core.telegram.org/bots/api#inlinequeryresultcachedphoto), and [InlineQueryResultCachedVideo](https://core.telegram.org/bots/api#inlinequeryresultcachedvideo).

2025-01-07 00:43 UTC, hameda169 commented on inline.ts
The field `provider_token` of class `InputInvoiceMessageContent` must become optional base on the [change log](https://core.telegram.org/bots/api-changelog#may-28-2024):
> The field provider_token in the class [InputInvoiceMessageContent](https://core.telegram.org/bots/api#inputinvoicemessagecontent) must be omitted for payments in [Telegram Stars](https://t.me/BotNews/90).

2025-01-07 00:43 UTC, hameda169 commented on message.ts
The parameter `provider_token` of methods `sendInvoice` and `createInvoiceLink` must become optional base on the [change log](https://core.telegram.org/bots/api-changelog#may-28-2024):
> The parameter provider_token of the methods [sendInvoice](https://core.telegram.org/bots/api#sendinvoice) and [createInvoiceLink](https://core.telegram.org/bots/api#createinvoicelink) must be omitted for payments in [Telegram Stars](https://t.me/BotNews/90).

2025-01-07 00:43 UTC, hameda169 commented on methods.ts
> -
I can see that these are back in the next commit but if you want to have a clean commit history, better to merge `Add methods and types for API 7.5` and `Adds PaidMedia types` commits. And also, move the `Paid Media` types to the `Add support for 7.6` commit. These are just suggestions.

2025-01-10 02:07 UTC, MKRhere commented
I'm very grateful to your work @danielrhodes and @hameda169. Since I've fallen back quite a bit, instead of incrementally updating via the changelog, I diffed an old version of the HTML page I had from before 7.1 and directly jumped to 8.2.

Closing this PR in favour of #8. Would love your feedback and reviews there. Thank you!

2025-01-10 02:07 UTC, closed without merging